# This is a basic workflow to help you get started with Actions

name: Testing user input workflow
on: 
  workflow_dispatch: 
    inputs: 
      number1:
        description: "First number"
        default: '0'
        required: true
      number2:
        description: "Second number"
        default: '0'
        required: true  
      
jobs:
 user_input_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Add number"
        id: sum
        run: echo "::set-output-name=sum::$((${{inputs.number1}} + ${{inputs.number2}}))"
      - name: "display Sum"
        run: echo "The sum of ${{inputs.number1}} and ${{inputs.number2}} is ${{steps.sum.outputs.sum}}"
        
